# -*- coding: utf-8 -*-
"""step3_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EvkmnnGCXoYKMOjMa1_zh1TppwvmlBkC
"""

import numpy as np

def split_train_val_test(input, labels):
  training_proportion = 0.80
  validation_proportion = 0.1
  num_train = int(len(input) * training_proportion)
  num_val = int(len(input) * validation_proportion)

  input_train, input_valid, input_test = input[:num_train], input[num_train:num_train+num_val], input[num_train+num_val:]
  label_train, label_valid, label_test = labels[:num_train], labels[num_train:num_train+num_val], labels[num_train+num_val:]

  return input_train, input_valid, input_test, label_train, label_valid, label_test